server:
  port: 8083

spring:
  application:
    name: audit-service
  datasource:
    url: jdbc:postgresql://localhost:5432/audit-services
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  cloud:
    function:
      definition: auditLogConsumer;errorLogConsumer
    stream:
      bindings:
        auditLogConsumer-in-0:
          destination: auditLog-out-0
          group: audit-service-group
        errorLogConsumer-in-0:
          destination: errorLog-out-0
          group: audit-service-group

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration-ms: 3600000