server:
  port: 8080

spring:
  jpa:
    auditing:
      enabled: false
  application:
    name: gateway-service
  web:
    resources:
      add-mappings: false
    mvc:
      problemdetails:
        enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration-ms: 3600000

application:
  services:
    auth-service:
      url: http://localhost:8081
    user-service:
      url: http://localhost:8082
    audit-service:
      url: http://localhost:8083

  cloud:
    function:
      definition: auditLogConsumer;errorLogConsumer
    stream:
      bindings:
        auditLog-out-0:
          destination: auditLog-out-0
        errorLog-out-0:
          destination: errorLog-out-0